### ISSUE TITLE
Support more providers out of the box

### ISSUE THREAD

**Issue by floriangaerber** [ArtistStudio/electron-oauthorize#3]
- [ ] GitHub
- [ ] Facebook
- [ ] Google (G+, YouTube)
- [ ] Instagram
- [ ] Twitch
- [ ] Patreon

**Comment by Vviizard** [comment]
[Wikipedia: List of OAuth providers](https://en.wikipedia.org/wiki/List_of_OAuth_providers)

**Comment by floriangaerber** [comment]
Project closed.
